config/routes.rb
Rails.application.routes.draw do

  get 'shifts/create'

  get 'shifts/destroy'

  get 'sessions/new'



resources :users
resources :events
resources :shifts do
	member do
		post :reject
		post :confirm
		post :accepted
	end
end

root 'static_pages#home'

get 'help' => 'static_pages#help'

get 'about' => 'static_pages#about'

get 'login' => 'sessions#new'

post 'login' => 'sessions#create'

delete 'logout' => 'sessions#destroy'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :shifts, dependent: :destroy
	has_many :users, through: :shifts

	validates :name, presence: true
	validates :date, presence: true
end

app/models/shift.rb
class Shift < ActiveRecord::Base
	
  belongs_to :event
  belongs_to :user

  scope :accepted, -> { where(status: 'accepted') }
  scope :confirmed, -> { where(status: 'confirmed') }
  scope :needsconfirmation, -> { where(status: 'needsconfirmation') }
  scope :rejected, -> { where(status: 'rejected') }
  scope :pending, -> { where(status: 'pending') }
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }

	validates :name, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 250 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, length: {minimum: 6}

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

	has_many :shifts
	has_many :events, through: :shifts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

	def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  
    @users = User.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

      if @event.save
          redirect_to @event
        else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
      end

  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update

    @event.update_attributes(event_params)
    redirect_to @event

  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy

    @event.destroy
    redirect_to events_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :location, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
      
  		redirect_to root_path
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
 		render 'new'
 	end
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  def new
  end

  def create
  		@shift = Shift.new(shift_params)
  		@event = Event.find(params[:shift][:event_id])
  		@user = User.find(params[:shift][:user_id])
  		@shift.event_id = @event.id
  		@shift.user_id = @user.id
  		@shift.location = @event.location
  		@shift.name = @event.name
      @shift.status = :pending

  		if @shift.save 
			 redirect_to @event
       else
          flash.now[:danger] = 'Invalid Shift'
          render 'new'
		end

  end

 
  def update
    @shift = Shift.find(params[:id])
    @event = @shift.event
    @shift.update_attributes(shift_params)
      redirect_to @event
  end

  def destroy
  	@shift = Shift.find(params[:id])
  	@event = @shift.event
  	@shift.destroy

  	redirect_to @event
  end

def accepted
     @shift = Shift.find(params[:id])
      @event = @shift.event
      @user = User.find_by(id: @shift.user_id)
      @shift.status = :accepted
      if @shift.save 
        redirect_to root_path
      else 
        
      end
  end

  def confirm
     @shift = Shift.find(params[:id])
      @event = @shift.event
      @user = User.find_by(id: @shift.user_id)
      @shift.status = :confirmed
      if @shift.save 
        redirect_to root_path
      else 
        
      end
  end

  def reject
      @shift = Shift.find(params[:id])
      @event = @shift.event
      @user = User.find_by(id: @shift.user_id)
      @shift.status = :rejected
      
      if @shift.save 
        redirect_to root_path
      else 
        
      end
  end

  private 

  def shift_params 

  	params.require(:shift).permit(:time, :location, :date, :user_id, :event_id, :status)

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if !logged_in?
  		redirect_to login_path
  	end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
          log_in(@user)
          redirect_to @user
        else
          flash.now[:danger] = 'Invalid email/password combination'
          render 'new'
      end

  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if @user.update_attributes(user_params)
      redirect_to @user
      else
          flash.now[:danger] = 'Nope'
          render 'users/new'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    redirect_to users_path

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin, :avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
   		@current_user = nil
	end
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
	<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.date_select :date %>

      <%= f.submit "Update Event", class: "btn btn-primary outline btn-block" %>
    <% end %>

  </div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>
<div class = "row">
<div class = "col-md-9">
<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.location %></td>
        <td><%= event.date %></td>
      <td>Confirmed: <%= event.shifts.confirmed.count %>/<%= (event.shifts.confirmed.count + event.shifts.needsconfirmation.count ) %> </td>
        <td><%= link_to 'Show', event, class: "btn btn-primary outline btn-sm" %></td>
        <td><%= link_to 'Edit', edit_event_path(event), class: "btn btn-primary outline btn-sm" %></td>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Event', new_event_path, class: "btn btn-primary outline btn-md" %>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

	<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control' %>

      <%= f.label :date %>
      <%= f.date_select :date %>
      <br>
      <%= f.submit "Create Event", class: "btn btn-primary outline btn-block" %>
    <% end %>

  </div>
</div>

app/views/events/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="row">
  <div class="col-md-6">
<p>
  <strong>Name:</strong> <h3><%= @event.name %></h3>
</p>

<p>
  <strong>Location:</strong> <h3><%= @event.location %></h3>
</p>
<p>
  <strong>Date:</strong> <h3><%= @event.date %></h3>
</p>

<% if logged_in? && current_user.admin? %>

 <% @users.each do |user| %>
  <%= user.name %>
  <% if user.shifts.where(:event_id => @event.id).any? %>
    <p> Already invited! </p>
    <% else %>

    <%= form_for(user.shifts.build) do |f| %>
    <%= f.hidden_field :user_id, :value => user.id %>
    <%= f.hidden_field :event_id, :value => @event.id %>
    <%= f.hidden_field :date, :value => @event.date %>


    <%= f.submit "Send Invite", class: "btn btn-primary btn-sm outline "  %>
    <% end %>
    <% end %>

 <% end %>

 <% end %>
 </div>
<div class="col-md-6">
	<% if @event.shifts.any? %>
    <h3>Pending:</h3>
		<% @event.shifts.pending.each do |shift| %>

		<p> <%= shift.user.name %> </p>
    <% if logged_in? && current_user.admin? %>
    <td><%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
    <% end %>
    <h3>Rejected:</h3>
    <% @event.shifts.rejected.each do |shift| %>
    <p><%= shift.user.name %></p>
    
		<% end %>

	<% end %>

</div>
</div>
<div class="row">
  <div class="col-md-9">
    <% if logged_in? && current_user.admin? %>
    <h3>Employees available to work:</h3>
    <% @event.shifts.accepted.each do |shift| %>
    <p><%= shift.user.name %>
      <%= shift.time %> 
      <%= form_for(shift) do |f| %>

      <%= f.time_select :time %>
      <%= f.hidden_field :status, :value => :needsconfirmation %>
      <%= f.submit "Send confirmation", class: "btn btn-primary btn-small outline" %>

      <% end %>
       <% end %>
      <%= render partial: "shifts/shift", collection: @event.shifts.needsconfirmation %>
    
    </p>
    
   
    <% end %>

    <h3>Employees confirmed to work:</h3>
    <% @event.shifts.confirmed.each do |shift| %>
    <p><%= shift.user.name %>
      <%= shift.time %> 
       <% if logged_in? && current_user.admin? %>
      <%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
      <% end %>
      <% end %>
  </div>

</div>
<p><%= link_to 'Back', events_path %></o>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RadishApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "MyRadish", root_path, id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li> <%= link_to "Hi there #{current_user.name}", root_path %> </li> 
              <% if current_user.admin? %>  
            <li><%= link_to "Users",   users_path %></li>
            <li><%= link_to "Events",   events_path %></li>
            <% end %>
            <li><%= link_to "Log out", logout_path, method: "delete" %> </li>
            
            <% else %>
            <li><%= link_to "Sign up!", new_user_path %> </li>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
    	<% flash.each do |message_type, message| %>
  		<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>

      
      <div class = "row">
      
      
      
      <%= yield %>

  </div>
 
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shifts/_edit.html.erb
<%= form_for(@shift) do |f| %>

   <div class="field">
    <%= f.time_select :time %><br>
    <%= f.label :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shifts/_shift.html.erb
<div class="row">
	<div class = "shift">
<p> <h3><%= shift.name %> : <%= shift.location %> : <%= shift.status.upcase %> </p>
<% if logged_in? && current_user.admin? %>
      <%= link_to 'Delete', shift, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
      <% end %>
</div>
</div>

app/views/shifts/create.html.erb
<h1>Shifts#create</h1>
<p>Find me in app/views/shifts/create.html.erb</p>

app/views/shifts/destroy.html.erb
<h1>Shifts#destroy</h1>
<p>Find me in app/views/shifts/destroy.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div id="home-background">

<h1>Hey you!</h1>
<p>Welcome to your new MyRadish website! Check your upcoming invites, shifts, or confirmations</p>

<% if logged_in? %>
	<div class="row">
		<div class="col-md-4">
			<h3>Upcoming:</h3>
			<div class= "shift">
				<% if current_user.shifts.confirmed.any? %>
				<% current_user.shifts.confirmed.each do |shift| %>
				<div class = "confirmed">
					<p><%= link_to shift.event.name, event_path(shift.event.id) %></p>
					<p><%= shift.event.location %></p>
					<p><%= shift.time.strftime(" %H:%M") %></p>
				</div>
				<% end %>
				<% else %>
				<p> You don't have any confirmed shifts right now. </p>
				<% end %>
			</div>
			</div>
		<div class ="col-md-4">
			<h3>To confirm:</h3>
			<div class="shift">
				<% current_user.shifts.needsconfirmation.each do |shift| %>
				<div class = "needs-confirmation">
					<p><%= shift.event.name %></p>
					<p><%= shift.event.location %></p>
					<p><%= shift.event.date %></p>
					<p><%= shift.time.strftime(" %H:%M") %></p>
					<p> <%= link_to "Confirm!", confirm_shift_path(shift), method: :post, class: 'btn btn-success' %>
				</div>
				<% end %>
			</div>
		</div>
		<div class ="col-md-4">
			<h3>Pending:</h3>
			<div class="shift">
				<% current_user.shifts.pending.each do |shift| %>
				<div class="pending">
					
					<p><%= shift.event.name %></p>
					<p><%= shift.event.location %></p>
					<p><%= shift.date %></p>
				
					<p> <%= link_to "No thanks!", reject_shift_path(shift), method: :post, class: 'btn btn-warning' %>
   					<p> <%= link_to "Sure!", accepted_shift_path(shift), method: :post, class: 'btn btn-success' %>
 
   					</div>
				<% end %>
			</div>
		</div>
	</div>
<% end %>

</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
   <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <%= f.file_field :avatar %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-9">
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user, class: 'btn btn-primary outline btn-sm' %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-primary outline btn-sm' %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New User', new_user_path, class: 'btn btn-primary outline btn-md' %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :admin, "Admin?" %>
      <%= f.check_box :admin %>


      <%= f.submit "Create my account", class: "btn btn-primary outline btn-block" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "row">
	<div class = "page-header">
	
 		 <h1><%= @user.name %> 
 		 <small> <%= @user.email %> </small></h1>
		
	</div>	
</div>
<div class = "row">
	<div class = "col-md-6">

		<div class = "center" id = "userpic" ><%= image_tag @user.avatar.url(:medium) %> </div>
		<h2>Contact:</h2>
<p>
<h2><span class="glyphicon glyphicon-envelope" aria-hidden="true">  </span> | Email</h2>
</p>
<p>
<h2><span class="glyphicon glyphicon-phone" aria-hidden="true"> </span> | (206) 555 - 5555</h2>
</p>
</div>

	<div class = "col-md-6">
		<h2>Shift summary:</h2>
<p>
	<% if @user.shifts.any? %>
<%= render partial: "shifts/shift", collection: @user.shifts %>
	<% end %>
</p>

</div>

</div>
<%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary outline btn-sm' %> |
<%= link_to 'Back', users_path %>